theme = "nord-dark"
icons = "awesome5"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
marquee = false
smart_trim = true


[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
notifier = "notifysend"

# [[block]]
# block = "toggle"
# text = "4k"
# command_state = "xrandr | grep DP1\\ connected\\ 38 | grep -v eDP1"
# command_on = "~/.screenlayout/4kmon_default.sh"
# command_off = "~/.screenlayout/builtin.sh"
# interval = 5

[[block]]
block = "net"
format = "{ssid} {speed_down;M*b} {speed_up;M*b}"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
format = "{icon} {percentage}"
unit = "GB"
interval = 20
warning = 80.0
alert = 90.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"


[[block]]
block = "nvidia_gpu"
label = "RTX3090"
show_memory = true
show_clocks = true
show_fan_speed = true
show_power_draw = true
interval = 1

[[block]]
allow_missing = true
hide_missing = true
block = "battery"
interval = 10
format = "{percentage} {time}"
driver = "apcaccess"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "custom"
command = "echo '{\"icon\":\"weather_thunder\",\"state\":\"Critical\", \"text\": \"Danger!\"}'"
json = true

[[block]]
block = "custom"
command = ''' echo 'hej' '''

[[block]]
block = "sound"

[[block]]
block = "sound"
device_kind = "source"
