#!/usr/bin/env bash

set -x

# ====== Variables =============================

# source ~/.cache/wal/colors.sh # pywal scheme - update if needed

# yabai template colours
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

# yabai -m config status_bar                   on
# yabai -m config status_bar_background_color  0xff$CBACK
# yabai -m config status_bar_foreground_color  0xff$CFORE



# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget

yabai -m signal --add event=space_changed action="osascript -e \"tell application id 'tracesOf.Uebersicht' to refresh widget id 'simple-bar-spaces-jsx'\""


yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff$CACTV
yabai -m config normal_window_border_color   0xff$CNORM
yabai -m config insert_window_border_color   0xff$CINSE


declare -A gaps
declare -A color

gaps["top"]="8"
gaps["bottom"]="8"
gaps["left"]="8"
gaps["right"]="8"
gaps["inner"]="8"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config external_bar all:23:0

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Stickies" app="^Stickies$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" manage=off space=4
yabai -m rule --add label="Calendar" app="^Calendar$" manage=off space=4
yabai -m rule --add label="Signal" app="^Signal$" manage=off space=4
yabai -m rule --add label="Microsoft Teams" app="^Microsoft Teams$" manage=off space=4
yabai -m rule --add label="WhatsApp" app="^WhatsApp$" manage=off space=4
yabai -m rule --add label="(Fiji Is Just) ImageJ" app="^ImageJ$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m rule --add label="Alacritty" app="^Alacritty$"
yabai -m rule --add label="Firefox" app="^Firefox$"
yabai -m rule --add label="Notion" app="^Notion$" space=9
yabai -m rule --add label="iTerm" app="^iTerm$"
yabai -m rule --add label="Spotify" app="^Spotify$" manage=on space=6
yabai -m rule --add label="Finder" app="^Finder$" manage=on
yabai -m rule --add label="OmniGraffle" app="^OmniGraffle$" manage=on space=3
yabai -m rule --add label="JupyterLab" app="^JupyterLab.*$" manage=on space=3

# ===== Signals ================================

set +x
printf "yabai: configuration loaded...\\n"


